// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/v1/api.proto

package apiv1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on IsAliveRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *IsAliveRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on IsAliveRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in IsAliveRequestMultiError,
// or nil if none found.
func (m *IsAliveRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *IsAliveRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Endpoint

	if len(errors) > 0 {
		return IsAliveRequestMultiError(errors)
	}

	return nil
}

// IsAliveRequestMultiError is an error wrapping multiple validation errors
// returned by IsAliveRequest.ValidateAll() if the designated constraints
// aren't met.
type IsAliveRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m IsAliveRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m IsAliveRequestMultiError) AllErrors() []error { return m }

// IsAliveRequestValidationError is the validation error returned by
// IsAliveRequest.Validate if the designated constraints aren't met.
type IsAliveRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e IsAliveRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e IsAliveRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e IsAliveRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e IsAliveRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e IsAliveRequestValidationError) ErrorName() string { return "IsAliveRequestValidationError" }

// Error satisfies the builtin error interface
func (e IsAliveRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sIsAliveRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = IsAliveRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = IsAliveRequestValidationError{}

// Validate checks the field values on IsAliveResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *IsAliveResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on IsAliveResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// IsAliveResponseMultiError, or nil if none found.
func (m *IsAliveResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *IsAliveResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Endpoint

	// no validation rules for IsAlive

	if len(errors) > 0 {
		return IsAliveResponseMultiError(errors)
	}

	return nil
}

// IsAliveResponseMultiError is an error wrapping multiple validation errors
// returned by IsAliveResponse.ValidateAll() if the designated constraints
// aren't met.
type IsAliveResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m IsAliveResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m IsAliveResponseMultiError) AllErrors() []error { return m }

// IsAliveResponseValidationError is the validation error returned by
// IsAliveResponse.Validate if the designated constraints aren't met.
type IsAliveResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e IsAliveResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e IsAliveResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e IsAliveResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e IsAliveResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e IsAliveResponseValidationError) ErrorName() string { return "IsAliveResponseValidationError" }

// Error satisfies the builtin error interface
func (e IsAliveResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sIsAliveResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = IsAliveResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = IsAliveResponseValidationError{}
