-- Create "device_status" table
CREATE TABLE "device_status" (
  "id" character varying NOT NULL,
  "status" character varying NOT NULL,
  "last_seen" character varying NOT NULL,
  PRIMARY KEY ("id")
);
-- Create "network_devices" table
CREATE TABLE "network_devices" (
  "id" character varying NOT NULL,
  "vendor" character varying NOT NULL,
  "model" character varying NOT NULL,
  "hw_version" character varying NOT NULL,
  PRIMARY KEY ("id")
);
-- Create "endpoints" table
CREATE TABLE "endpoints" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "host" character varying NOT NULL,
  "port" character varying NOT NULL,
  "protocol" character varying NOT NULL,
  "network_device_endpoints" character varying NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "endpoints_network_devices_endpoints" FOREIGN KEY ("network_device_endpoints") REFERENCES "network_devices" ("id") ON UPDATE NO ACTION ON DELETE SET NULL
);
-- Create "versions" table
CREATE TABLE "versions" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "version" character varying NOT NULL,
  "checksum" character varying NOT NULL,
  "network_device_sw_version" character varying NULL,
  "network_device_fw_version" character varying NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "versions_network_devices_fw_version" FOREIGN KEY ("network_device_fw_version") REFERENCES "network_devices" ("id") ON UPDATE NO ACTION ON DELETE SET NULL,
  CONSTRAINT "versions_network_devices_sw_version" FOREIGN KEY ("network_device_sw_version") REFERENCES "network_devices" ("id") ON UPDATE NO ACTION ON DELETE SET NULL
);
