// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/eroshiva/trade-show-poc/internal/ent/devicestatus"
	"github.com/eroshiva/trade-show-poc/internal/ent/networkdevice"
)

// DeviceStatus is the model entity for the DeviceStatus schema.
type DeviceStatus struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Status holds the value of the "status" field.
	Status devicestatus.Status `json:"status,omitempty"`
	// LastSeen holds the value of the "last_seen" field.
	LastSeen string `json:"last_seen,omitempty"`
	// ConsequentialFailedConnectivityAttempts holds the value of the "consequentialFailedConnectivityAttempts" field.
	ConsequentialFailedConnectivityAttempts int32 `json:"consequentialFailedConnectivityAttempts,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the DeviceStatusQuery when eager-loading is set.
	Edges                        DeviceStatusEdges `json:"edges"`
	device_status_network_device *string
	selectValues                 sql.SelectValues
}

// DeviceStatusEdges holds the relations/edges for other nodes in the graph.
type DeviceStatusEdges struct {
	// NetworkDevice holds the value of the network_device edge.
	NetworkDevice *NetworkDevice `json:"network_device,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// NetworkDeviceOrErr returns the NetworkDevice value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DeviceStatusEdges) NetworkDeviceOrErr() (*NetworkDevice, error) {
	if e.NetworkDevice != nil {
		return e.NetworkDevice, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: networkdevice.Label}
	}
	return nil, &NotLoadedError{edge: "network_device"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*DeviceStatus) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case devicestatus.FieldConsequentialFailedConnectivityAttempts:
			values[i] = new(sql.NullInt64)
		case devicestatus.FieldID, devicestatus.FieldStatus, devicestatus.FieldLastSeen:
			values[i] = new(sql.NullString)
		case devicestatus.ForeignKeys[0]: // device_status_network_device
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the DeviceStatus fields.
func (ds *DeviceStatus) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case devicestatus.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				ds.ID = value.String
			}
		case devicestatus.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				ds.Status = devicestatus.Status(value.String)
			}
		case devicestatus.FieldLastSeen:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_seen", values[i])
			} else if value.Valid {
				ds.LastSeen = value.String
			}
		case devicestatus.FieldConsequentialFailedConnectivityAttempts:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field consequentialFailedConnectivityAttempts", values[i])
			} else if value.Valid {
				ds.ConsequentialFailedConnectivityAttempts = int32(value.Int64)
			}
		case devicestatus.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field device_status_network_device", values[i])
			} else if value.Valid {
				ds.device_status_network_device = new(string)
				*ds.device_status_network_device = value.String
			}
		default:
			ds.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the DeviceStatus.
// This includes values selected through modifiers, order, etc.
func (ds *DeviceStatus) Value(name string) (ent.Value, error) {
	return ds.selectValues.Get(name)
}

// QueryNetworkDevice queries the "network_device" edge of the DeviceStatus entity.
func (ds *DeviceStatus) QueryNetworkDevice() *NetworkDeviceQuery {
	return NewDeviceStatusClient(ds.config).QueryNetworkDevice(ds)
}

// Update returns a builder for updating this DeviceStatus.
// Note that you need to call DeviceStatus.Unwrap() before calling this method if this DeviceStatus
// was returned from a transaction, and the transaction was committed or rolled back.
func (ds *DeviceStatus) Update() *DeviceStatusUpdateOne {
	return NewDeviceStatusClient(ds.config).UpdateOne(ds)
}

// Unwrap unwraps the DeviceStatus entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ds *DeviceStatus) Unwrap() *DeviceStatus {
	_tx, ok := ds.config.driver.(*txDriver)
	if !ok {
		panic("ent: DeviceStatus is not a transactional entity")
	}
	ds.config.driver = _tx.drv
	return ds
}

// String implements the fmt.Stringer.
func (ds *DeviceStatus) String() string {
	var builder strings.Builder
	builder.WriteString("DeviceStatus(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ds.ID))
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", ds.Status))
	builder.WriteString(", ")
	builder.WriteString("last_seen=")
	builder.WriteString(ds.LastSeen)
	builder.WriteString(", ")
	builder.WriteString("consequentialFailedConnectivityAttempts=")
	builder.WriteString(fmt.Sprintf("%v", ds.ConsequentialFailedConnectivityAttempts))
	builder.WriteByte(')')
	return builder.String()
}

// DeviceStatusSlice is a parsable slice of DeviceStatus.
type DeviceStatusSlice []*DeviceStatus
