// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/eroshiva/trade-show-poc/internal/ent/devicestatus"
	"github.com/eroshiva/trade-show-poc/internal/ent/predicate"
)

// DeviceStatusQuery is the builder for querying DeviceStatus entities.
type DeviceStatusQuery struct {
	config
	ctx        *QueryContext
	order      []devicestatus.OrderOption
	inters     []Interceptor
	predicates []predicate.DeviceStatus
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the DeviceStatusQuery builder.
func (dsq *DeviceStatusQuery) Where(ps ...predicate.DeviceStatus) *DeviceStatusQuery {
	dsq.predicates = append(dsq.predicates, ps...)
	return dsq
}

// Limit the number of records to be returned by this query.
func (dsq *DeviceStatusQuery) Limit(limit int) *DeviceStatusQuery {
	dsq.ctx.Limit = &limit
	return dsq
}

// Offset to start from.
func (dsq *DeviceStatusQuery) Offset(offset int) *DeviceStatusQuery {
	dsq.ctx.Offset = &offset
	return dsq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (dsq *DeviceStatusQuery) Unique(unique bool) *DeviceStatusQuery {
	dsq.ctx.Unique = &unique
	return dsq
}

// Order specifies how the records should be ordered.
func (dsq *DeviceStatusQuery) Order(o ...devicestatus.OrderOption) *DeviceStatusQuery {
	dsq.order = append(dsq.order, o...)
	return dsq
}

// First returns the first DeviceStatus entity from the query.
// Returns a *NotFoundError when no DeviceStatus was found.
func (dsq *DeviceStatusQuery) First(ctx context.Context) (*DeviceStatus, error) {
	nodes, err := dsq.Limit(1).All(setContextOp(ctx, dsq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{devicestatus.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (dsq *DeviceStatusQuery) FirstX(ctx context.Context) *DeviceStatus {
	node, err := dsq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first DeviceStatus ID from the query.
// Returns a *NotFoundError when no DeviceStatus ID was found.
func (dsq *DeviceStatusQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = dsq.Limit(1).IDs(setContextOp(ctx, dsq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{devicestatus.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (dsq *DeviceStatusQuery) FirstIDX(ctx context.Context) string {
	id, err := dsq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single DeviceStatus entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one DeviceStatus entity is found.
// Returns a *NotFoundError when no DeviceStatus entities are found.
func (dsq *DeviceStatusQuery) Only(ctx context.Context) (*DeviceStatus, error) {
	nodes, err := dsq.Limit(2).All(setContextOp(ctx, dsq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{devicestatus.Label}
	default:
		return nil, &NotSingularError{devicestatus.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (dsq *DeviceStatusQuery) OnlyX(ctx context.Context) *DeviceStatus {
	node, err := dsq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only DeviceStatus ID in the query.
// Returns a *NotSingularError when more than one DeviceStatus ID is found.
// Returns a *NotFoundError when no entities are found.
func (dsq *DeviceStatusQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = dsq.Limit(2).IDs(setContextOp(ctx, dsq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{devicestatus.Label}
	default:
		err = &NotSingularError{devicestatus.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (dsq *DeviceStatusQuery) OnlyIDX(ctx context.Context) string {
	id, err := dsq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of DeviceStatusSlice.
func (dsq *DeviceStatusQuery) All(ctx context.Context) ([]*DeviceStatus, error) {
	ctx = setContextOp(ctx, dsq.ctx, ent.OpQueryAll)
	if err := dsq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*DeviceStatus, *DeviceStatusQuery]()
	return withInterceptors[[]*DeviceStatus](ctx, dsq, qr, dsq.inters)
}

// AllX is like All, but panics if an error occurs.
func (dsq *DeviceStatusQuery) AllX(ctx context.Context) []*DeviceStatus {
	nodes, err := dsq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of DeviceStatus IDs.
func (dsq *DeviceStatusQuery) IDs(ctx context.Context) (ids []string, err error) {
	if dsq.ctx.Unique == nil && dsq.path != nil {
		dsq.Unique(true)
	}
	ctx = setContextOp(ctx, dsq.ctx, ent.OpQueryIDs)
	if err = dsq.Select(devicestatus.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (dsq *DeviceStatusQuery) IDsX(ctx context.Context) []string {
	ids, err := dsq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (dsq *DeviceStatusQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, dsq.ctx, ent.OpQueryCount)
	if err := dsq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, dsq, querierCount[*DeviceStatusQuery](), dsq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (dsq *DeviceStatusQuery) CountX(ctx context.Context) int {
	count, err := dsq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (dsq *DeviceStatusQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, dsq.ctx, ent.OpQueryExist)
	switch _, err := dsq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (dsq *DeviceStatusQuery) ExistX(ctx context.Context) bool {
	exist, err := dsq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the DeviceStatusQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (dsq *DeviceStatusQuery) Clone() *DeviceStatusQuery {
	if dsq == nil {
		return nil
	}
	return &DeviceStatusQuery{
		config:     dsq.config,
		ctx:        dsq.ctx.Clone(),
		order:      append([]devicestatus.OrderOption{}, dsq.order...),
		inters:     append([]Interceptor{}, dsq.inters...),
		predicates: append([]predicate.DeviceStatus{}, dsq.predicates...),
		// clone intermediate query.
		sql:  dsq.sql.Clone(),
		path: dsq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Status devicestatus.Status `json:"status,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.DeviceStatus.Query().
//		GroupBy(devicestatus.FieldStatus).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (dsq *DeviceStatusQuery) GroupBy(field string, fields ...string) *DeviceStatusGroupBy {
	dsq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &DeviceStatusGroupBy{build: dsq}
	grbuild.flds = &dsq.ctx.Fields
	grbuild.label = devicestatus.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Status devicestatus.Status `json:"status,omitempty"`
//	}
//
//	client.DeviceStatus.Query().
//		Select(devicestatus.FieldStatus).
//		Scan(ctx, &v)
func (dsq *DeviceStatusQuery) Select(fields ...string) *DeviceStatusSelect {
	dsq.ctx.Fields = append(dsq.ctx.Fields, fields...)
	sbuild := &DeviceStatusSelect{DeviceStatusQuery: dsq}
	sbuild.label = devicestatus.Label
	sbuild.flds, sbuild.scan = &dsq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a DeviceStatusSelect configured with the given aggregations.
func (dsq *DeviceStatusQuery) Aggregate(fns ...AggregateFunc) *DeviceStatusSelect {
	return dsq.Select().Aggregate(fns...)
}

func (dsq *DeviceStatusQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range dsq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, dsq); err != nil {
				return err
			}
		}
	}
	for _, f := range dsq.ctx.Fields {
		if !devicestatus.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if dsq.path != nil {
		prev, err := dsq.path(ctx)
		if err != nil {
			return err
		}
		dsq.sql = prev
	}
	return nil
}

func (dsq *DeviceStatusQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*DeviceStatus, error) {
	var (
		nodes = []*DeviceStatus{}
		_spec = dsq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*DeviceStatus).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &DeviceStatus{config: dsq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, dsq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (dsq *DeviceStatusQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := dsq.querySpec()
	_spec.Node.Columns = dsq.ctx.Fields
	if len(dsq.ctx.Fields) > 0 {
		_spec.Unique = dsq.ctx.Unique != nil && *dsq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, dsq.driver, _spec)
}

func (dsq *DeviceStatusQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(devicestatus.Table, devicestatus.Columns, sqlgraph.NewFieldSpec(devicestatus.FieldID, field.TypeString))
	_spec.From = dsq.sql
	if unique := dsq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if dsq.path != nil {
		_spec.Unique = true
	}
	if fields := dsq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, devicestatus.FieldID)
		for i := range fields {
			if fields[i] != devicestatus.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := dsq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := dsq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := dsq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := dsq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (dsq *DeviceStatusQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(dsq.driver.Dialect())
	t1 := builder.Table(devicestatus.Table)
	columns := dsq.ctx.Fields
	if len(columns) == 0 {
		columns = devicestatus.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if dsq.sql != nil {
		selector = dsq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if dsq.ctx.Unique != nil && *dsq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range dsq.predicates {
		p(selector)
	}
	for _, p := range dsq.order {
		p(selector)
	}
	if offset := dsq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := dsq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// DeviceStatusGroupBy is the group-by builder for DeviceStatus entities.
type DeviceStatusGroupBy struct {
	selector
	build *DeviceStatusQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (dsgb *DeviceStatusGroupBy) Aggregate(fns ...AggregateFunc) *DeviceStatusGroupBy {
	dsgb.fns = append(dsgb.fns, fns...)
	return dsgb
}

// Scan applies the selector query and scans the result into the given value.
func (dsgb *DeviceStatusGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, dsgb.build.ctx, ent.OpQueryGroupBy)
	if err := dsgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DeviceStatusQuery, *DeviceStatusGroupBy](ctx, dsgb.build, dsgb, dsgb.build.inters, v)
}

func (dsgb *DeviceStatusGroupBy) sqlScan(ctx context.Context, root *DeviceStatusQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(dsgb.fns))
	for _, fn := range dsgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*dsgb.flds)+len(dsgb.fns))
		for _, f := range *dsgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*dsgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := dsgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// DeviceStatusSelect is the builder for selecting fields of DeviceStatus entities.
type DeviceStatusSelect struct {
	*DeviceStatusQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (dss *DeviceStatusSelect) Aggregate(fns ...AggregateFunc) *DeviceStatusSelect {
	dss.fns = append(dss.fns, fns...)
	return dss
}

// Scan applies the selector query and scans the result into the given value.
func (dss *DeviceStatusSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, dss.ctx, ent.OpQuerySelect)
	if err := dss.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DeviceStatusQuery, *DeviceStatusSelect](ctx, dss.DeviceStatusQuery, dss, dss.inters, v)
}

func (dss *DeviceStatusSelect) sqlScan(ctx context.Context, root *DeviceStatusQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(dss.fns))
	for _, fn := range dss.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*dss.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := dss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
