// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/eroshiva/trade-show-poc/internal/ent/endpoint"
	"github.com/eroshiva/trade-show-poc/internal/ent/networkdevice"
	"github.com/eroshiva/trade-show-poc/internal/ent/predicate"
)

// EndpointUpdate is the builder for updating Endpoint entities.
type EndpointUpdate struct {
	config
	hooks    []Hook
	mutation *EndpointMutation
}

// Where appends a list predicates to the EndpointUpdate builder.
func (eu *EndpointUpdate) Where(ps ...predicate.Endpoint) *EndpointUpdate {
	eu.mutation.Where(ps...)
	return eu
}

// SetHost sets the "host" field.
func (eu *EndpointUpdate) SetHost(s string) *EndpointUpdate {
	eu.mutation.SetHost(s)
	return eu
}

// SetNillableHost sets the "host" field if the given value is not nil.
func (eu *EndpointUpdate) SetNillableHost(s *string) *EndpointUpdate {
	if s != nil {
		eu.SetHost(*s)
	}
	return eu
}

// SetPort sets the "port" field.
func (eu *EndpointUpdate) SetPort(s string) *EndpointUpdate {
	eu.mutation.SetPort(s)
	return eu
}

// SetNillablePort sets the "port" field if the given value is not nil.
func (eu *EndpointUpdate) SetNillablePort(s *string) *EndpointUpdate {
	if s != nil {
		eu.SetPort(*s)
	}
	return eu
}

// SetProtocol sets the "protocol" field.
func (eu *EndpointUpdate) SetProtocol(e endpoint.Protocol) *EndpointUpdate {
	eu.mutation.SetProtocol(e)
	return eu
}

// SetNillableProtocol sets the "protocol" field if the given value is not nil.
func (eu *EndpointUpdate) SetNillableProtocol(e *endpoint.Protocol) *EndpointUpdate {
	if e != nil {
		eu.SetProtocol(*e)
	}
	return eu
}

// SetNetworkDeviceID sets the "network_device" edge to the NetworkDevice entity by ID.
func (eu *EndpointUpdate) SetNetworkDeviceID(id string) *EndpointUpdate {
	eu.mutation.SetNetworkDeviceID(id)
	return eu
}

// SetNillableNetworkDeviceID sets the "network_device" edge to the NetworkDevice entity by ID if the given value is not nil.
func (eu *EndpointUpdate) SetNillableNetworkDeviceID(id *string) *EndpointUpdate {
	if id != nil {
		eu = eu.SetNetworkDeviceID(*id)
	}
	return eu
}

// SetNetworkDevice sets the "network_device" edge to the NetworkDevice entity.
func (eu *EndpointUpdate) SetNetworkDevice(n *NetworkDevice) *EndpointUpdate {
	return eu.SetNetworkDeviceID(n.ID)
}

// Mutation returns the EndpointMutation object of the builder.
func (eu *EndpointUpdate) Mutation() *EndpointMutation {
	return eu.mutation
}

// ClearNetworkDevice clears the "network_device" edge to the NetworkDevice entity.
func (eu *EndpointUpdate) ClearNetworkDevice() *EndpointUpdate {
	eu.mutation.ClearNetworkDevice()
	return eu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (eu *EndpointUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, eu.sqlSave, eu.mutation, eu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (eu *EndpointUpdate) SaveX(ctx context.Context) int {
	affected, err := eu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (eu *EndpointUpdate) Exec(ctx context.Context) error {
	_, err := eu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (eu *EndpointUpdate) ExecX(ctx context.Context) {
	if err := eu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (eu *EndpointUpdate) check() error {
	if v, ok := eu.mutation.Protocol(); ok {
		if err := endpoint.ProtocolValidator(v); err != nil {
			return &ValidationError{Name: "protocol", err: fmt.Errorf(`ent: validator failed for field "Endpoint.protocol": %w`, err)}
		}
	}
	return nil
}

func (eu *EndpointUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := eu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(endpoint.Table, endpoint.Columns, sqlgraph.NewFieldSpec(endpoint.FieldID, field.TypeString))
	if ps := eu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := eu.mutation.Host(); ok {
		_spec.SetField(endpoint.FieldHost, field.TypeString, value)
	}
	if value, ok := eu.mutation.Port(); ok {
		_spec.SetField(endpoint.FieldPort, field.TypeString, value)
	}
	if value, ok := eu.mutation.Protocol(); ok {
		_spec.SetField(endpoint.FieldProtocol, field.TypeEnum, value)
	}
	if eu.mutation.NetworkDeviceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   endpoint.NetworkDeviceTable,
			Columns: []string{endpoint.NetworkDeviceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(networkdevice.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := eu.mutation.NetworkDeviceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   endpoint.NetworkDeviceTable,
			Columns: []string{endpoint.NetworkDeviceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(networkdevice.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, eu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{endpoint.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	eu.mutation.done = true
	return n, nil
}

// EndpointUpdateOne is the builder for updating a single Endpoint entity.
type EndpointUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EndpointMutation
}

// SetHost sets the "host" field.
func (euo *EndpointUpdateOne) SetHost(s string) *EndpointUpdateOne {
	euo.mutation.SetHost(s)
	return euo
}

// SetNillableHost sets the "host" field if the given value is not nil.
func (euo *EndpointUpdateOne) SetNillableHost(s *string) *EndpointUpdateOne {
	if s != nil {
		euo.SetHost(*s)
	}
	return euo
}

// SetPort sets the "port" field.
func (euo *EndpointUpdateOne) SetPort(s string) *EndpointUpdateOne {
	euo.mutation.SetPort(s)
	return euo
}

// SetNillablePort sets the "port" field if the given value is not nil.
func (euo *EndpointUpdateOne) SetNillablePort(s *string) *EndpointUpdateOne {
	if s != nil {
		euo.SetPort(*s)
	}
	return euo
}

// SetProtocol sets the "protocol" field.
func (euo *EndpointUpdateOne) SetProtocol(e endpoint.Protocol) *EndpointUpdateOne {
	euo.mutation.SetProtocol(e)
	return euo
}

// SetNillableProtocol sets the "protocol" field if the given value is not nil.
func (euo *EndpointUpdateOne) SetNillableProtocol(e *endpoint.Protocol) *EndpointUpdateOne {
	if e != nil {
		euo.SetProtocol(*e)
	}
	return euo
}

// SetNetworkDeviceID sets the "network_device" edge to the NetworkDevice entity by ID.
func (euo *EndpointUpdateOne) SetNetworkDeviceID(id string) *EndpointUpdateOne {
	euo.mutation.SetNetworkDeviceID(id)
	return euo
}

// SetNillableNetworkDeviceID sets the "network_device" edge to the NetworkDevice entity by ID if the given value is not nil.
func (euo *EndpointUpdateOne) SetNillableNetworkDeviceID(id *string) *EndpointUpdateOne {
	if id != nil {
		euo = euo.SetNetworkDeviceID(*id)
	}
	return euo
}

// SetNetworkDevice sets the "network_device" edge to the NetworkDevice entity.
func (euo *EndpointUpdateOne) SetNetworkDevice(n *NetworkDevice) *EndpointUpdateOne {
	return euo.SetNetworkDeviceID(n.ID)
}

// Mutation returns the EndpointMutation object of the builder.
func (euo *EndpointUpdateOne) Mutation() *EndpointMutation {
	return euo.mutation
}

// ClearNetworkDevice clears the "network_device" edge to the NetworkDevice entity.
func (euo *EndpointUpdateOne) ClearNetworkDevice() *EndpointUpdateOne {
	euo.mutation.ClearNetworkDevice()
	return euo
}

// Where appends a list predicates to the EndpointUpdate builder.
func (euo *EndpointUpdateOne) Where(ps ...predicate.Endpoint) *EndpointUpdateOne {
	euo.mutation.Where(ps...)
	return euo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (euo *EndpointUpdateOne) Select(field string, fields ...string) *EndpointUpdateOne {
	euo.fields = append([]string{field}, fields...)
	return euo
}

// Save executes the query and returns the updated Endpoint entity.
func (euo *EndpointUpdateOne) Save(ctx context.Context) (*Endpoint, error) {
	return withHooks(ctx, euo.sqlSave, euo.mutation, euo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (euo *EndpointUpdateOne) SaveX(ctx context.Context) *Endpoint {
	node, err := euo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (euo *EndpointUpdateOne) Exec(ctx context.Context) error {
	_, err := euo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (euo *EndpointUpdateOne) ExecX(ctx context.Context) {
	if err := euo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (euo *EndpointUpdateOne) check() error {
	if v, ok := euo.mutation.Protocol(); ok {
		if err := endpoint.ProtocolValidator(v); err != nil {
			return &ValidationError{Name: "protocol", err: fmt.Errorf(`ent: validator failed for field "Endpoint.protocol": %w`, err)}
		}
	}
	return nil
}

func (euo *EndpointUpdateOne) sqlSave(ctx context.Context) (_node *Endpoint, err error) {
	if err := euo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(endpoint.Table, endpoint.Columns, sqlgraph.NewFieldSpec(endpoint.FieldID, field.TypeString))
	id, ok := euo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Endpoint.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := euo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, endpoint.FieldID)
		for _, f := range fields {
			if !endpoint.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != endpoint.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := euo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := euo.mutation.Host(); ok {
		_spec.SetField(endpoint.FieldHost, field.TypeString, value)
	}
	if value, ok := euo.mutation.Port(); ok {
		_spec.SetField(endpoint.FieldPort, field.TypeString, value)
	}
	if value, ok := euo.mutation.Protocol(); ok {
		_spec.SetField(endpoint.FieldProtocol, field.TypeEnum, value)
	}
	if euo.mutation.NetworkDeviceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   endpoint.NetworkDeviceTable,
			Columns: []string{endpoint.NetworkDeviceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(networkdevice.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := euo.mutation.NetworkDeviceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   endpoint.NetworkDeviceTable,
			Columns: []string{endpoint.NetworkDeviceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(networkdevice.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Endpoint{config: euo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, euo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{endpoint.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	euo.mutation.done = true
	return _node, nil
}
