// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// DeviceStatus is the predicate function for devicestatus builders.
type DeviceStatus func(*sql.Selector)

// Endpoint is the predicate function for endpoint builders.
type Endpoint func(*sql.Selector)

// NetworkDevice is the predicate function for networkdevice builders.
type NetworkDevice func(*sql.Selector)

// Version is the predicate function for version builders.
type Version func(*sql.Selector)
