// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: pkg/mocks/simulator.proto

package simulatorv1

import (
	monitoring "github.com/eroshiva/trade-show-poc/api/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetHWModelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHWModelResponse) Reset() {
	*x = GetHWModelResponse{}
	mi := &file_pkg_mocks_simulator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHWModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHWModelResponse) ProtoMessage() {}

func (x *GetHWModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_mocks_simulator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHWModelResponse.ProtoReflect.Descriptor instead.
func (*GetHWModelResponse) Descriptor() ([]byte, []int) {
	return file_pkg_mocks_simulator_proto_rawDescGZIP(), []int{0}
}

func (x *GetHWModelResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_pkg_mocks_simulator_proto protoreflect.FileDescriptor

const file_pkg_mocks_simulator_proto_rawDesc = "" +
	"\n" +
	"\x19pkg/mocks/simulator.proto\x12\fsimulator.v1\x1a\x17api/v1/monitoring.proto\x1a\x1bgoogle/protobuf/empty.proto\".\n" +
	"\x12GetHWModelResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion2\x90\x02\n" +
	"\x11MockDeviceService\x12;\n" +
	"\tGetStatus\x12\x16.google.protobuf.Empty\x1a\x14.api.v1.DeviceStatus\"\x00\x12H\n" +
	"\n" +
	"GetHWModel\x12\x16.google.protobuf.Empty\x1a .simulator.v1.GetHWModelResponse\"\x00\x129\n" +
	"\fGetSWVersion\x12\x16.google.protobuf.Empty\x1a\x0f.api.v1.Version\"\x00\x129\n" +
	"\fGetFWVersion\x12\x16.google.protobuf.Empty\x1a\x0f.api.v1.Version\"\x00BAZ?github.com/eroshiva/trade-show-poc/api/v1/simulator;simulatorv1b\x06proto3"

var (
	file_pkg_mocks_simulator_proto_rawDescOnce sync.Once
	file_pkg_mocks_simulator_proto_rawDescData []byte
)

func file_pkg_mocks_simulator_proto_rawDescGZIP() []byte {
	file_pkg_mocks_simulator_proto_rawDescOnce.Do(func() {
		file_pkg_mocks_simulator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_mocks_simulator_proto_rawDesc), len(file_pkg_mocks_simulator_proto_rawDesc)))
	})
	return file_pkg_mocks_simulator_proto_rawDescData
}

var file_pkg_mocks_simulator_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pkg_mocks_simulator_proto_goTypes = []any{
	(*GetHWModelResponse)(nil),      // 0: simulator.v1.GetHWModelResponse
	(*emptypb.Empty)(nil),           // 1: google.protobuf.Empty
	(*monitoring.DeviceStatus)(nil), // 2: api.v1.DeviceStatus
	(*monitoring.Version)(nil),      // 3: api.v1.Version
}
var file_pkg_mocks_simulator_proto_depIdxs = []int32{
	1, // 0: simulator.v1.MockDeviceService.GetStatus:input_type -> google.protobuf.Empty
	1, // 1: simulator.v1.MockDeviceService.GetHWModel:input_type -> google.protobuf.Empty
	1, // 2: simulator.v1.MockDeviceService.GetSWVersion:input_type -> google.protobuf.Empty
	1, // 3: simulator.v1.MockDeviceService.GetFWVersion:input_type -> google.protobuf.Empty
	2, // 4: simulator.v1.MockDeviceService.GetStatus:output_type -> api.v1.DeviceStatus
	0, // 5: simulator.v1.MockDeviceService.GetHWModel:output_type -> simulator.v1.GetHWModelResponse
	3, // 6: simulator.v1.MockDeviceService.GetSWVersion:output_type -> api.v1.Version
	3, // 7: simulator.v1.MockDeviceService.GetFWVersion:output_type -> api.v1.Version
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_mocks_simulator_proto_init() }
func file_pkg_mocks_simulator_proto_init() {
	if File_pkg_mocks_simulator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_mocks_simulator_proto_rawDesc), len(file_pkg_mocks_simulator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_mocks_simulator_proto_goTypes,
		DependencyIndexes: file_pkg_mocks_simulator_proto_depIdxs,
		MessageInfos:      file_pkg_mocks_simulator_proto_msgTypes,
	}.Build()
	File_pkg_mocks_simulator_proto = out.File
	file_pkg_mocks_simulator_proto_goTypes = nil
	file_pkg_mocks_simulator_proto_depIdxs = nil
}
