apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "network-device-simulator.labels" . | nindent 4 }}
spec:
  # This service must be created separately and be "headless"
  serviceName: "{{ .Release.Name }}-svc"
  replicas: 4 # We want four distinct simulators
  selector:
    matchLabels:
      # Use the standard selector labels helper
      {{- include "network-device-simulator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        # Use the standard selector labels helper
        {{- include "network-device-simulator.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        # --- You only need ONE container definition ---
        - name: network-device-simulator
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          ports:
            - containerPort: 50151
              name: grpc
          # Pass the Pod's unique name as an environment variable
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: DEVICE_SIMULATOR_GRPC_SERVER_ADDRESS
              value: {{ .Values.config.serverAddress | quote }}
            - name: DEVICE_SIMULATOR_DEVICE_STATUS
              value: {{ .Values.config.deviceStatus | quote }}
          # The command to launch your single simulator binary
          command: ["/usr/local/bin/nd-simulator"]
---
# Headless service for stable DNS records (This part is correct)
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-svc"
spec:
  clusterIP: None # This makes it a headless service
  selector:
    # The service selector must use the standard helper as well
    {{- include "network-device-simulator.selectorLabels" . | nindent 4 }}
  ports:
    - port: 50151
      name: grpc